### ISSUE TITLE
403 error on styles.css (and other CDN files) when previewing and deploying

### ISSUE THREAD

**Issue by SamBenson** [dixahq/kb-javascript-starter#10]
I've followed the instructions in the Deployment article and, as far as I can see, I've done everything correctly but when I preview or deploy my theme it just says "Loading" and in the network tab, I can see 403 errors on anything coming from the CDN. I've checked to make sure my auth token is correct and I'm using the permanent one but it still looks to be an issue. 

![image](https://user-images.githubusercontent.com/136246/126071590-e4d617ab-6e6a-4409-b2a5-c9e5d50c3d79.png)

Any idea what I might have done wrong?

**Comment by kristian-puccio** [comment]
Hi @SamBenson thanks for trying out the Kb-kit and reporting the issue you have found.
Do you mind letting me know the url of the KB you are running on so I can take a look for you?

If you would like to send any info that you don't want on github feel free to send an email to support@elev.io.

Thanks,
Kristian

**Comment by SamBenson** [comment]
Thanks Kristian, I sent the URL to Nathan in support a couple of days ago. Did you get it?

**Comment by SamBenson** [comment]
@kristian-puccio I've managed to narrow the issue down to me using SCSS - having removed that and switch to standard CSS it appears to be working.

**Comment by kristian-puccio** [comment]
Yes @SamBenson got the URL thanks for that.

Interesting find with the SCSS, did you end up adding a post-css plugin to handle the SCSS or did you add some config to the Webpack plugin?

If so do you mind letting me know the config you used so I can try replicate?

Thanks,
Kristian

**Comment by SamBenson** [comment]
I added the SCSS plugin as it says in the docs (although had some issues with the `MiniCssExtractPlugin` loader so removed the reference to it). I also added a URL loader to handle background images. Locally everything worked fine but previews and deployments were where it fell apart. 

```
module.exports = async (config, { mode }) => {
  config.module.rules.push({
		test: /\.(png|jpg|gif|svg)$/i,
		use: [
			{
				loader: 'url-loader',
				options: {
					limit: false,
				},
			},
		],
	});

	config.module.rules.push({
		test: /\.scss$/,
		use: [
			{
                                loader:'style-loader'
			},
			"css-loader",
			'resolve-url-loader',
			"sass-loader",
		],
	});
	return config;
};
```

**Comment by kristian-puccio** [comment]
Heya @SamBenson,

Thanks for that, I've added this issue to our support queue and will get to this next week.
Is that ok, or is this a blocker for you?

**Comment by kristian-puccio** [comment]
@SamBenson I've found the issue(s).

`MiniCssExtractPlugin` is required to create the final css file that is uploaded to the server, that's why the server was responding with 403, the style.css file wasn't being created and thus not uploaded.

But to get MiniCssExtractPlugin to work we just needed to import it correctly, I've updated the docs so the import is now there. You can just add this to the top of your webpack.config.js file and it will work.

```
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
```

Sorry about that and thanks again for reporting!
